services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bankmatch
      POSTGRES_USER: bankmatch
      POSTGRES_PASSWORD: bankmatch
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
