name: CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose Up
        run: docker compose -f infra/compose.yaml up -d db
      - name: Wait for DB
        run: sleep 5
      - name: Migrate
        run: docker compose -f infra/compose.yaml exec -T db psql -U bankmatch -d bankmatch -f /migrations/0001_init.sql
      - name: Ingest
        run: docker compose -f infra/compose.yaml run --rm etl bash -lc "pip install -r app/requirements.txt && python etl/ingest_csv.py --dsn postgres://bankmatch:bankmatch@db:5432/bankmatch --csv data/templates/products_template.csv"
